# 📊 Análisis Exploratorio de Ventas y Comportamiento de Clientes

**Estudiante:** KELY PACHECO  
**Módulo:** Friendly SQL & Python para Analytics  
**Diploma:** Diploma Data Analyst  

---

## 🎯 Objetivo

Analizar el comportamiento de las ventas y los clientes de FerreMarket Perú,
identificando patrones relacionados con:

- Ventas netas
- Productos y categorías
- Segmentos de clientes
- Regiones
- Canales de venta
- Descuentos
- Margen
- Evolución temporal

El objetivo final es obtener insights que permitan apoyar la toma de decisiones
comerciales y mejorar la rentabilidad.

## 🏢 Preguntas del negocio

FerreMarket Perú es una empresa dedicada a la comercialización de productos
de ferretería y construcción a través de diferentes canales de venta.

El análisis busca responder preguntas como:

1. ¿Qué categorías generan mayores ventas?
2. ¿Qué regiones presentan mayor facturación?
3. ¿Qué canales son más importantes?
4. ¿Qué segmentos generan mayor ticket?
5. ¿Existe relación entre descuentos y margen?
6. ¿Cómo evolucionan las ventas en el tiempo?
7. ¿Qué oportunidades comerciales pueden identificarse?

In [ ]:
!pip -q install duckdb plotly

In [ ]:
import pandas as pd
import numpy as np
import duckdb
import plotly.express as px
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

1. Carga y exploración inicial de los datos
En esta etapa se carga el dataset y se realiza una primera revisión de su estructura, cantidad de registros, variables y tipos de datos.

In [ ]:
df = pd.read_csv(
    "/content/dataset_ventas.csv",
    parse_dates=["Fecha"]
)

print("Dataset cargado correctamente.")
print(f"Cantidad de registros: {df.shape[0]:,}")
print(f"Cantidad de variables: {df.shape[1]}")

Dataset cargado correctamente.
Cantidad de registros: 3,000
Cantidad de variables: 14

In [ ]:
print("Primeros 5 registros:")
display(df.head())

Primeros 5 registros:

,VentaID,Fecha,ClienteID,Segmento,Producto,Categoria,Region,Canal,Cantidad,PrecioUnitario,Descuento,VentaNeta,Margen,MedioPago
0,V00001,2024-03-03,C0349,Hogar,Martillo profesional,Herramientas,Arequipa,App,6,65,0.03,378.30,116.85,Efectivo
1,V00002,2024-12-31,C0186,Empresa,Brocha 3 pulgadas,Pinturas,Piura,App,6,18,0.00,108.00,23.66,Transferencia
2,V00003,2025-10-11,C0032,Profesional,Foco LED,Electricidad,Junín,App,4,15,0.00,60.00,14.52,Transferencia
3,V00004,2025-05-10,C0390,Hogar,Brocha 3 pulgadas,Pinturas,Cusco,Tienda,3,18,0.10,48.60,15.38,Plin
4,V00005,2024-09-25,C0484,Hogar,Foco LED,Electricidad,La Libertad,Web,2,15,0.05,28.50,8.09,Yape

In [ ]:
print("Últimos 5 registros:")
display(df.tail())

Últimos 5 registros:

,VentaID,Fecha,ClienteID,Segmento,Producto,Categoria,Region,Canal,Cantidad,PrecioUnitario,Descuento,VentaNeta,Margen,MedioPago
2995,V02996,2025-02-26,C0148,Hogar,Cemento 42.5kg,Construcción,Cusco,Tienda,5,32,0.05,152.00,32.88,Efectivo
2996,V02997,2025-03-13,C0399,Hogar,Guantes de trabajo,Seguridad,Lima,Web,4,22,0.03,85.36,28.79,Transferencia
2997,V02998,2025-06-14,C0433,Profesional,Llave de paso,Plomería,Cusco,Web,6,28,0.10,151.20,42.90,Yape
2998,V02999,2025-09-10,C0057,Hogar,Taladro inalámbrico,Herramientas,La Libertad,Tienda,6,260,0.00,"1,560.00",359.96,Efectivo
2999,V03000,2025-10-12,C0456,Profesional,Martillo profesional,Herramientas,La Libertad,Tienda,6,65,0.03,378.30,100.62,Efectivo

In [ ]:
print("Información general:")
df.info()

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   VentaID         3000 non-null   object
 1   Fecha           3000 non-null   datetime64[ns]
 2   ClienteID       3000 non-null   object
 3   Segmento        3000 non-null   object
 4   Producto        3000 non-null   object
 5   Categoria       3000 non-null   object
 6   Region          3000 non-null   object
 7   Canal           3000 non-null   object
 8   Cantidad        3000 non-null   int64
 9   PrecioUnitario  3000 non-null   int64
 10  Descuento       3000 non-null   float64
 11  VentaNeta       3000 non-null   float64
 12  Margen          3000 non-null   float64
 13  MedioPago       3000 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(8)
memory usage: 328.3+ KB

In [ ]:
print("Variables del dataset:")

for columna in df.columns:
    print("-", columna)

Variables del dataset:
- VentaID
- Fecha
- ClienteID
- Segmento
- Producto
- Categoria
- Region
- Canal
- Cantidad
- PrecioUnitario
- Descuento
- VentaNeta
- Margen
- MedioPago

In [ ]:
print("Dimensiones del dataset:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]}")

Dimensiones del dataset:
Filas: 3,000
Columnas: 14

### 🔎 Interpretación

El dataset contiene registros de operaciones comerciales y variables
relacionadas con fecha, producto, categoría, segmento, región, canal,
cantidad, descuento, ventas netas y margen.

Esta estructura permite realizar un análisis multidimensional del desempeño
comercial.

In [ ]:
calidad = pd.DataFrame({
    "Tipo de dato": df.dtypes.astype(str),
    "Valores nulos": df.isna().sum(),
    "% nulos": (df.isna().mean() * 100).round(2),
    "Valores únicos": df.nunique()
})

display(calidad)

                  Tipo de dato  Valores nulos  % nulos  Valores únicos
VentaID                 object              0     0.00            3000
Fecha           datetime64[ns]              0     0.00             723
ClienteID               object              0     0.00             499
Segmento                object              0     0.00               3
Producto                object              0     0.00              12
Categoria               object              0     0.00               6
Region                  object              0     0.00               6
Canal                   object              0     0.00               4
Cantidad                 int64              0     0.00               7
PrecioUnitario           int64              0     0.00              12
Descuento              float64              0     0.00               5
VentaNeta              float64              0     0.00             352
Margen                 float64              0     0.00            2473
MedioPago               object              0     0.00               5

In [ ]:
print(
    "Duplicados:",
    df.duplicated().sum()
)

Duplicados: 0

In [ ]:
columnas_texto = df.select_dtypes(include="object").columns

for col in columnas_texto:
    vacios = df[col].astype(str).str.strip().eq("").sum()
    print(f"{col}: {vacios:,} valores vacíos")

VentaID: 0 valores vacíos
ClienteID: 0 valores vacíos
Segmento: 0 valores vacíos
Producto: 0 valores vacíos
Categoria: 0 valores vacíos
Region: 0 valores vacíos
Canal: 0 valores vacíos
MedioPago: 0 valores vacíos

## 2. Validación de variables numéricas

Se revisan las principales variables numéricas para detectar valores
negativos, ceros o valores potencialmente inconsistentes.

In [ ]:
variables_numericas = [
    "Cantidad",
    "Descuento",
    "VentaNeta",
    "Margen"
]

for columna in variables_numericas:
    print(f"\n--- {columna} ---")
    print(f"Mínimo: {df[columna].min():,.2f}")
    print(f"Máximo: {df[columna].max():,.2f}")
    print(f"Promedio: {df[columna].mean():,.2f}")
    print(f"Valores negativos: {(df[columna] < 0).sum():,}")

--- Cantidad ---
Mínimo: 1.00
Máximo: 7.00
Promedio: 3.96
Valores negativos: 0

--- Descuento ---
Mínimo: 0.00
Máximo: 0.10
Promedio: 0.04
Valores negativos: 0

--- VentaNeta ---
Mínimo: 7.20
Máximo: 1,820.00
Promedio: 203.59
Valores negativos: 0

--- Margen ---
Mínimo: 0.93
Máximo: 582.68
Promedio: 47.59
Valores negativos: 0

In [ ]:
print("Estadísticas descriptivas de variables numéricas:")

display(
    df[variables_numericas].describe().T
)

Estadísticas descriptivas de variables numéricas:

             count   mean    std  min   25%    50%    75%      max
Cantidad  3,000.00   3.96   2.01 1.00  2.00   4.00   6.00     7.00
Descuento 3,000.00   0.04   0.03 0.00  0.00   0.05   0.05     0.10
VentaNeta 3,000.00 203.59 290.88 7.20 56.00 108.64 212.80 1,820.00
Margen    3,000.00  47.59  73.39 0.93 11.63  24.43  50.37   582.68

In [ ]:
variables_categoricas = [
    "Producto",
    "Categoria",
    "Segmento",
    "Region",
    "Canal"
]

for columna in variables_categoricas:
    print(f"\n{columna}")
    print(df[columna].value_counts().head(10))

Producto
Producto
Cemento 42.5kg          273
Casco de seguridad      260
Martillo profesional    257
Tubo PVC 1/2            257
Brocha 3 pulgadas       254
Foco LED                254
Taladro inalámbrico     248
Llave de paso           247
Pintura látex 4L        245
Alicate                 244
Name: count, dtype: int64

Categoria
Categoria
Herramientas    749
Plomería        504
Seguridad       500
Pinturas        499
Electricidad    475
Construcción    273
Name: count, dtype: int64

Segmento
Segmento
Hogar          1351
Profesional    1186
Empresa         463
Name: count, dtype: int64

Region
Region
Arequipa       535
La Libertad    512
Lima           508
Junín          492
Piura          483
Cusco          470
Name: count, dtype: int64

Canal
Canal
Tienda         1279
Web             751
App             545
Marketplace     425
Name: count, dtype: int64

In [ ]:
df["Año"] = df["Fecha"].dt.year
df["Mes"] = df["Fecha"].dt.month
df["NombreMes"] = df["Fecha"].dt.month_name()

In [ ]:
df["MargenPct"] = np.where(
    df["VentaNeta"] != 0,
    (df["Margen"] / df["VentaNeta"]) * 100,
    0
)

display(
    df[
        ["VentaNeta", "Margen", "MargenPct"]
    ].head()
)

   VentaNeta  Margen  MargenPct
0     378.30  116.85      30.89
1     108.00   23.66      21.91
2      60.00   14.52      24.20
3      48.60   15.38      31.65
4      28.50    8.09      28.39

In [ ]:
for col in df.select_dtypes(include="object").columns:
    print(
        col,
        ":",
        (df[col].astype(str).str.strip() == "").sum()
    )

VentaID : 0
ClienteID : 0
Segmento : 0
Producto : 0
Categoria : 0
Region : 0
Canal : 0
MedioPago : 0
NombreMes : 0

In [ ]:
df.describe()

,Fecha,Cantidad,PrecioUnitario,Descuento,VentaNeta,Margen,Año,Mes,MargenPct
count,3000,"3,000.00","3,000.00","3,000.00","3,000.00","3,000.00","3,000.00","3,000.00","3,000.00"
mean,2024-12-30 17:08:09.600000256,3.96,54.49,0.04,203.59,47.59,"2,024.50",6.55,23.04
min,2024-01-01 00:00:00,1.00,8.00,0.00,7.20,0.93,"2,024.00",1.00,12.00
25%,2024-07-01 00:00:00,2.00,18.00,0.00,56.00,11.63,"2,024.00",4.00,17.45
50%,2024-12-27 00:00:00,4.00,32.00,0.05,108.64,24.43,"2,024.00",7.00,23.26
75%,2025-07-07 00:00:00,6.00,47.75,0.05,212.80,50.37,"2,025.00",9.00,28.50
max,2025-12-31 00:00:00,7.00,260.00,0.10,"1,820.00",582.68,"2,025.00",12.00,33.98
std,NaN,2.01,65.73,0.03,290.88,73.39,0.50,3.46,6.33

In [ ]:
df.describe(include="object")

,VentaID,ClienteID,Segmento,Producto,Categoria,Region,Canal,MedioPago,NombreMes
count,3000,3000,3000,3000,3000,3000,3000,3000,3000
unique,3000,499,3,12,6,6,4,5,12
top,V03000,C0469,Hogar,Cemento 42.5kg,Herramientas,Arequipa,Tienda,Efectivo,September
freq,1,18,1351,273,749,535,1279,626,279

### Variables relevantes

Las principales variables consideradas son Fecha, Producto, Categoría, Segmento, Región, Canal, Cantidad, Descuento, VentaNeta y Margen.

Estas variables permiten analizar el comportamiento comercial desde una perspectiva temporal, geográfica, de producto, cliente y rentabilidad.

In [ ]:
kpis = pd.Series({
    "Total de operaciones": len(df),
    "Ventas netas": df["VentaNeta"].sum(),
    "Ticket promedio": df["VentaNeta"].mean(),
    "Margen total": df["Margen"].sum(),
    "Margen promedio": df["Margen"].mean(),
    "Margen %": (df["Margen"].sum() / df["VentaNeta"].sum()) * 100
})

display(kpis.to_frame("Valor"))

                          Valor
Total de operaciones   3,000.00
Ventas netas         610,764.01
Ticket promedio          203.59
Margen total         142,757.19
Margen promedio           47.59
Margen %                  23.37

In [ ]:
ventas_categoria = (
    df.groupby("Categoria", as_index=False)["VentaNeta"]
      .sum()
      .sort_values("VentaNeta", ascending=False)
)

ventas_categoria["ParticipacionPct"] = (
    ventas_categoria["VentaNeta"] /
    ventas_categoria["VentaNeta"].sum() * 100
)

fig = px.bar(
    ventas_categoria,
    x="Categoria",
    y="VentaNeta",
    text="VentaNeta",
    title="Ventas netas por categoría"
)

fig.update_traces(
    texttemplate="S/ %{text:,.0f}",
    textposition="outside"
)

fig.show()

### 🔎 Interpretación

La categoría Herramientas es la categoría de mayor venta neta representa el principal motor de facturación de la empresa. Sin embargo, una categoría con mayores ventas no necesariamente es la más rentable, por lo que debe compararse
también con su margen porcentual.

In [ ]:
ventas_mensuales = (
    df.groupby(pd.Grouper(key="Fecha", freq="ME"))["VentaNeta"]
      .sum()
      .reset_index()
)

fig = px.line(
    ventas_mensuales,
    x="Fecha",
    y="VentaNeta",
    markers=True,
    title="Evolución mensual de ventas netas"
)

fig.update_yaxes(tickprefix="S/ ")

fig.show()

### 🔎 Interpretación

La evolución mensual permite identificar períodos de crecimiento,
disminución o posibles patrones estacionales en las ventas.

Los meses con caídas importantes deben analizarse junto con canal,
región y categoría para identificar las posibles causas.

In [ ]:
ventas_canal = (
    df.groupby("Canal", as_index=False)["VentaNeta"]
      .sum()
      .sort_values("VentaNeta", ascending=False)
)

fig = px.pie(
    ventas_canal,
    names="Canal",
    values="VentaNeta",
    hole=0.45,
    title="Participación de ventas por canal"
)

fig.show()

### 🔎 Interpretación

El canal de Tiendas cuenta con mayor participación representa el principal punto de generación de ingresos. La empresa debería monitorear su evolución y evaluar si existe dependencia excesiva de un único canal.

In [ ]:
fig = px.histogram(
    df,
    x="VentaNeta",
    nbins=40,
    title="Distribución de las ventas netas por operación"
)

fig.show()

### 🔎 Interpretación

La distribución se concentra en operaciones de importes menores a 200 soles.

In [ ]:
ticket_segmento = (
    df.groupby("Segmento")["VentaNeta"]
      .mean()
      .sort_values(ascending=False)
)

segmento_top = ticket_segmento.idxmax()
ticket_promedio_top = ticket_segmento.max()

print(
    f"El segmento con mayor ticket promedio es "
    f"{segmento_top}, con S/ {ticket_promedio_top:,.2f}."
)

El segmento con mayor ticket promedio es Profesional, con S/ 208.70.

In [ ]:
ticket_segmento_df = (
    ticket_segmento
    .reset_index()
    .rename(columns={"VentaNeta": "TicketPromedio"})
)

fig = px.bar(
    ticket_segmento_df,
    x="Segmento",
    y="TicketPromedio",
    text="TicketPromedio",
    title="Ticket promedio por segmento"
)

fig.update_traces(
    texttemplate="S/ %{text:,.2f}",
    textposition="outside"
)

fig.show()

### 🔎 Interpretación

El ticket promedio muestra qué segmento Profesional genera operaciones de mayor valor, .esto debe contrastarse con el segmento que genra el mayor número de operaciones.

In [ ]:
fig = px.scatter(
    df,
    x="Descuento",
    y="MargenPct",
    size="VentaNeta",
    color="Categoria",
    hover_data=[
        "Producto",
        "Canal",
        "Segmento"
    ],
    title="Relación entre descuento y margen porcentual"
)

fig.show()

In [ ]:
mensual = (
    df.set_index("Fecha")
    .resample("ME")["VentaNeta"]
    .sum()
    .reset_index()
)

fig = px.line(
    mensual,
    x="Fecha",
    y="VentaNeta",
    markers=True,
    title="Evolución mensual de ventas"
)

fig.show()

### 🔎 Interpretación

El gráfico permite evaluar si mayores descuentos están asociados con una
reducción del margen porcentual.

Las operaciones de alto valor y bajo margen deben ser analizadas con especial
atención, ya que podrían estar generando ventas importantes sin contribuir
proporcionalmente a la rentabilidad.

Análisis de rentabilidad
 ¿La categoría que más vende también es la más rentable?

In [ ]:
rentabilidad_categoria = (
    df.groupby("Categoria", as_index=False)
      .agg(
          Ventas=("VentaNeta", "sum"),
          Margen=("Margen", "sum"),
          Operaciones=("VentaNeta", "count")
      )
)
rentabilidad_categoria["MargenPct"] = (
    rentabilidad_categoria["Margen"] / rentabilidad_categoria["Ventas"] * 100
)
display(rentabilidad_categoria.sort_values("Ventas", ascending=False))

      Categoria     Ventas    Margen  Operaciones  MargenPct
2  Herramientas 334,223.18 78,833.36          749      23.59
3      Pinturas 105,126.30 24,221.20          499      23.04
5     Seguridad  55,459.89 12,874.11          500      23.21
1  Electricidad  49,747.32 11,553.50          475      23.22
0  Construcción  33,756.16  7,728.77          273      22.90
4      Plomería  32,451.16  7,546.25          504      23.25

In [ ]:
fig = px.scatter(
    rentabilidad_categoria,
    x="Ventas", y="MargenPct", size="Margen", text="Categoria",
    title="Ventas vs margen porcentual por categoría"
)
fig.update_traces(textposition="top center")
fig.show()

cat_mas_ventas = rentabilidad_categoria.loc[rentabilidad_categoria["Ventas"].idxmax()]
cat_mayor_margen_pct = rentabilidad_categoria.loc[rentabilidad_categoria["MargenPct"].idxmax()]

print(f"Mayor venta: {cat_mas_ventas['Categoria']} → S/ {cat_mas_ventas['Ventas']:,.2f}")
print(f"Mayor margen porcentual: {cat_mayor_margen_pct['Categoria']} → {cat_mayor_margen_pct['MargenPct']:.2f}%")

if cat_mas_ventas["Categoria"] == cat_mayor_margen_pct["Categoria"]:
    print("Conclusión: la categoría líder en ventas también lidera en margen porcentual.")
else:
    print("Conclusión: la categoría líder en ventas NO es la misma que lidera en margen porcentual.")

Mayor venta: Herramientas → S/ 334,223.18
Mayor margen porcentual: Herramientas → 23.59%
Conclusión: la categoría líder en ventas también lidera en margen porcentual.

### 🔎 Interpretación

Este análisis permite identificar categorías que combinan alto volumen de
ventas con buena rentabilidad y aquellas que generan muchas ventas pero
presentan un margen porcentual reducido.

La segunda situación representa una oportunidad para revisar precios,
descuentos, costos y estrategia comercial.

7. 👥 Análisis de comportamiento de clientes

In [ ]:
clientes = (
    df.groupby("ClienteID", as_index=False)
      .agg(
          Operaciones=("VentaID", "count"),
          Ventas=("VentaNeta", "sum"),
          TicketPromedio=("VentaNeta", "mean"),
          Margen=("Margen", "sum")
      )
      .sort_values("Ventas", ascending=False)
)
clientes["MargenPct"] = clientes["Margen"] / clientes["Ventas"] * 100
display(clientes.head(10))

    ClienteID  Operaciones   Ventas  TicketPromedio   Margen  MargenPct
188     C0189           12 5,545.59          462.13 1,464.63      26.41
140     C0141            7 4,484.77          640.68   993.44      22.15
467     C0469           18 4,413.59          245.20 1,029.45      23.32
430     C0432            6 4,308.75          718.12   953.92      22.14
428     C0430            7 4,167.40          595.34   988.17      23.71
53      C0054            6 4,000.20          666.70 1,174.77      29.37
276     C0277            8 3,940.60          492.57   877.21      22.26
411     C0412            6 3,831.60          638.60 1,088.16      28.40
310     C0311           11 3,769.00          342.64   984.91      26.13
306     C0307            9 3,719.61          413.29   875.43      23.54

In [ ]:
top_clientes = clientes.head(10).sort_values("Ventas")

fig = px.bar(
    top_clientes, x="Ventas", y="ClienteID", orientation="h",
    text="Ventas", title="Top 10 clientes por ventas"
)
fig.update_traces(texttemplate="S/ %{text:,.0f}", textposition="outside")
fig.show()

cliente_top = clientes.iloc[0]
print(
    f"Insight: {cliente_top['ClienteID']} es el cliente de mayor venta acumulada: "
    f"S/ {cliente_top['Ventas']:,.2f} en {int(cliente_top['Operaciones'])} operaciones."
)

Insight: C0189 es el cliente de mayor venta acumulada: S/ 5,545.59 en 12 operaciones.

# 3. Análisis mediante SQL

Se utiliza DuckDB para realizar consultas SQL sobre el DataFrame y obtener
información agregada desde diferentes perspectivas comerciales.

In [ ]:
q1 = duckdb.query("""
SELECT *
FROM df
LIMIT 10
""").to_df()

display(q1)

,VentaID,Fecha,ClienteID,Segmento,Producto,Categoria,Region,Canal,Cantidad,PrecioUnitario,Descuento,VentaNeta,Margen,MedioPago,Año,Mes,NombreMes,MargenPct
0,V00001,2024-03-03,C0349,Hogar,Martillo profesional,Herramientas,Arequipa,App,6,65,0.03,378.30,116.85,Efectivo,2024,3,March,30.89
1,V00002,2024-12-31,C0186,Empresa,Brocha 3 pulgadas,Pinturas,Piura,App,6,18,0.00,108.00,23.66,Transferencia,2024,12,December,21.91
2,V00003,2025-10-11,C0032,Profesional,Foco LED,Electricidad,Junín,App,4,15,0.00,60.00,14.52,Transferencia,2025,10,October,24.20
3,V00004,2025-05-10,C0390,Hogar,Brocha 3 pulgadas,Pinturas,Cusco,Tienda,3,18,0.10,48.60,15.38,Plin,2025,5,May,31.65
4,V00005,2024-09-25,C0484,Hogar,Foco LED,Electricidad,La Libertad,Web,2,15,0.05,28.50,8.09,Yape,2024,9,September,28.39
5,V00006,2024-08-29,C0114,Profesional,Alicate,Herramientas,La Libertad,App,2,38,0.00,76.00,17.07,Plin,2024,8,August,22.46
6,V00007,2024-11-14,C0403,Hogar,Cable eléctrico 10m,Electricidad,La Libertad,App,5,42,0.03,203.70,61.74,Yape,2024,11,November,30.31
7,V00008,2025-08-05,C0394,Profesional,Cable eléctrico 10m,Electricidad,Cusco,App,1,42,0.00,42.00,5.11,Transferencia,2025,8,August,12.17
8,V00009,2024-06-28,C0058,Profesional,Foco LED,Electricidad,Arequipa,Web,4,15,0.05,57.00,8.59,Plin,2024,6,June,15.07
9,V00010,2024-03-07,C0280,Hogar,Taladro inalámbrico,Herramientas,Arequipa,Web,6,260,0.05,"1,482.00",358.33,Tarjeta,2024,3,March,24.18

### 🔎 Interpretación

La consulta permite validar mediante SQL la estructura y contenido de los
registros disponibles en el dataset.

Ventas Web superiores a S/ 500

In [ ]:
q2 = duckdb.query("""
SELECT
    VentaID,
    Fecha,
    ClienteID,
    Producto,
    Categoria,
    VentaNeta,
    Margen
FROM df
WHERE Canal = 'Web'
  AND VentaNeta > 500
ORDER BY VentaNeta DESC
LIMIT 20
""").to_df()
display(q2)

,VentaID,Fecha,ClienteID,Producto,Categoria,VentaNeta,Margen
0,V01928,2025-01-15,C0412,Taladro inalámbrico,Herramientas,"1,820.00",529.86
1,V02296,2024-08-30,C0141,Taladro inalámbrico,Herramientas,"1,820.00",550.72
2,V00368,2025-04-13,C0376,Taladro inalámbrico,Herramientas,"1,820.00",441.66
3,V00363,2024-04-14,C0189,Taladro inalámbrico,Herramientas,"1,729.00",504.73
4,V00296,2025-12-12,C0130,Taladro inalámbrico,Herramientas,"1,729.00",576.88
5,V02918,2024-07-30,C0390,Taladro inalámbrico,Herramientas,"1,729.00",400.87
6,V02682,2024-12-11,C0238,Taladro inalámbrico,Herramientas,"1,729.00",538.52
7,V00267,2025-06-11,C0430,Taladro inalámbrico,Herramientas,"1,729.00",450.55
8,V01685,2025-12-28,C0313,Taladro inalámbrico,Herramientas,"1,560.00",433.00
9,V00329,2025-11-29,C0365,Taladro inalámbrico,Herramientas,"1,560.00",188.87
10,V01682,2025-06-20,C0189,Taladro inalámbrico,Herramientas,"1,560.00",263.65
11,V02441,2025-04-10,C0469,Taladro inalámbrico,Herramientas,"1,513.20",322.44
12,V01452,2024-04-10,C0074,Taladro inalámbrico,Herramientas,"1,513.20",429.43
13,V01458,2024-06-18,C0211,Taladro inalámbrico,Herramientas,"1,482.00",428.69
14,V00010,2024-03-07,C0280,Taladro inalámbrico,Herramientas,"1,482.00",358.33
15,V00156,2024-03-17,C0241,Taladro inalámbrico,Herramientas,"1,435.20",413.01
16,V01368,2024-10-17,C0209,Taladro inalámbrico,Herramientas,"1,300.00",343.17
17,V01335,2025-09-10,C0003,Taladro inalámbrico,Herramientas,"1,261.00",166.25
18,V01336,2025-12-15,C0350,Taladro inalámbrico,Herramientas,"1,261.00",382.55
19,V01416,2025-01-05,C0160,Taladro inalámbrico,Herramientas,"1,235.00",362.22

### 🔎 Interpretación

La consulta identifica operaciones de alto valor realizadas mediante el canal
Web, permitiendo analizar posteriormente qué productos, categorías o segmentos
están asociados con las ventas digitales de mayor importe.

Ventas y margen por categoría

In [ ]:
q3 = duckdb.query("""
SELECT
    Categoria,
    COUNT(*) AS Operaciones,
    SUM(VentaNeta) AS Ventas,
    SUM(Margen) AS Margen,
    ROUND(SUM(Margen) / NULLIF(SUM(VentaNeta), 0) * 100, 2) AS MargenPct
FROM df
GROUP BY Categoria
ORDER BY Ventas DESC
""").to_df()
display(q3)

      Categoria  Operaciones     Ventas    Margen  MargenPct
0  Herramientas          749 334,223.18 78,833.36      23.59
1      Pinturas          499 105,126.30 24,221.20      23.04
2     Seguridad          500  55,459.89 12,874.11      23.21
3  Electricidad          475  49,747.32 11,553.50      23.22
4  Construcción          273  33,756.16  7,728.77      22.90
5      Plomería          504  32,451.16  7,546.25      23.25

Ventas por región

In [ ]:
q4 = duckdb.query("""
SELECT
    Region,
    COUNT(*) AS Operaciones,
    SUM(VentaNeta) AS VentasTotales,
    ROUND(AVG(VentaNeta), 2) AS TicketPromedio,
    SUM(Margen) AS MargenTotal
FROM df
GROUP BY Region
ORDER BY VentasTotales DESC
""").to_df()
display(q4)

        Region  Operaciones  VentasTotales  TicketPromedio  MargenTotal
0        Junín          492     112,198.12          228.04    26,186.23
1  La Libertad          512     110,441.43          215.71    25,627.63
2     Arequipa          535     102,090.19          190.82    24,269.32
3        Piura          483      98,406.14          203.74    23,757.24
4         Lima          508      97,161.58          191.26    22,160.64
5        Cusco          470      90,466.55          192.48    20,756.13

Canal y segmento

In [ ]:
q5 = duckdb.query("""
SELECT
    Canal,
    Segmento,
    COUNT(*) AS Operaciones,
    SUM(VentaNeta) AS Ventas,
    ROUND(AVG(VentaNeta), 2) AS TicketPromedio,
    ROUND(AVG(Descuento) * 100, 2) AS DescuentoPromedioPct,
    ROUND(AVG(Margen), 2) AS MargenPromedio
FROM df
GROUP BY Canal, Segmento
ORDER BY Ventas DESC
""").to_df()
display(q5)

,Canal,Segmento,Operaciones,Ventas,TicketPromedio,DescuentoPromedioPct,MargenPromedio
0,Tienda,Hogar,577,"114,306.66",198.11,4.10,46.63
1,Tienda,Profesional,502,"102,813.59",204.81,4.39,48.56
2,Web,Hogar,342,"64,696.28",189.17,4.22,43.88
3,Web,Profesional,303,"63,764.38",210.44,4.06,50.41
4,App,Hogar,242,"49,330.31",203.84,4.23,47.59
5,Marketplace,Profesional,180,"42,543.08",236.35,4.14,52.95
6,Marketplace,Hogar,190,"42,123.48",221.70,4.12,49.28
7,Tienda,Empresa,200,"41,053.70",205.27,4.28,49.65
8,App,Profesional,201,"38,399.68",191.04,4.21,44.24
9,Web,Empresa,106,"21,112.69",199.18,5.17,43.63
10,App,Empresa,102,"20,356.69",199.58,4.71,48.71
11,Marketplace,Empresa,55,"10,263.47",186.61,5.02,42.97

Top 10 clientes mediante SQL

In [ ]:
q6 = duckdb.query("""
SELECT
    ClienteID,
    COUNT(*) AS Operaciones,
    SUM(VentaNeta) AS Ventas,
    SUM(Margen) AS Margen,
    ROUND(AVG(VentaNeta), 2) AS TicketPromedio
FROM df
GROUP BY ClienteID
ORDER BY Ventas DESC
LIMIT 10
""").to_df()
display(q6)

  ClienteID  Operaciones   Ventas   Margen  TicketPromedio
0     C0189           12 5,545.59 1,464.63          462.13
1     C0141            7 4,484.77   993.44          640.68
2     C0469           18 4,413.59 1,029.45          245.20
3     C0432            6 4,308.75   953.92          718.13
4     C0430            7 4,167.40   988.17          595.34
5     C0054            6 4,000.20 1,174.77          666.70
6     C0277            8 3,940.60   877.21          492.58
7     C0412            6 3,831.60 1,088.16          638.60
8     C0311           11 3,769.00   984.91          342.64
9     C0307            9 3,719.61   875.43          413.29

In [ ]:
categoria_top = ventas_categoria.iloc[0]

print(
    f"La categoría con mayores ventas es "
    f"{categoria_top['Categoria']} con "
    f"S/ {categoria_top['VentaNeta']:,.2f}."
)

La categoría con mayores ventas es Herramientas con S/ 334,223.18.

In [ ]:
canal_top = ventas_canal.iloc[0]

print(
    f"El canal con mayores ventas es "
    f"{canal_top['Canal']} con "
    f"S/ {canal_top['VentaNeta']:,.2f}."
)

El canal con mayores ventas es Tienda con S/ 258,173.95.

In [ ]:
ventas_region = (
    df.groupby("Region", as_index=False)
      .agg(
          Ventas=("VentaNeta", "sum"),
          Margen=("Margen", "sum"),
          Operaciones=("VentaNeta", "count")
      )
      .sort_values("Ventas", ascending=False)
)

region_top = ventas_region.iloc[0]

print(
    f"La región con mayores ventas es "
    f"{region_top['Region']} con "
    f"S/ {region_top['Ventas']:,.2f}."
)

La región con mayores ventas es Junín con S/ 112,198.12.

In [ ]:
print(
    f"El segmento con mayor ticket promedio es "
    f"{segmento_top}, con "
    f"S/ {ticket_promedio_top:,.2f} por operación."
)

El segmento con mayor ticket promedio es Profesional, con S/ 208.70 por operación.

# 4. Conclusiones
A partir del análisis exploratorio realizado mediante Python y SQL se
identificaron los principales patrones relacionados con las ventas,
segmentos, regiones, canales y rentabilidad.

Los principales puntos identificados fueron:

1. Existe una categoría que concentra una proporción importante de las ventas.
2. Un canal representa una participación relevante del negocio.
3. Algunas regiones presentan mayor concentración de facturación.
4. Los segmentos presentan diferencias en su ticket promedio.
5. Los descuentos deben analizarse conjuntamente con el margen para evitar
   interpretar el crecimiento de ventas como sinónimo de mayor rentabilidad.
6. El análisis de ventas y margen permite identificar oportunidades
   comerciales que no serían visibles observando únicamente la facturación.

# 5. Recomendaciones de negocio

## 1. Priorizar las categorías de alto margen

Identificar las categorías que combinan alto volumen de ventas y alto margen
porcentual para priorizar acciones comerciales.

## 2. Revisar descuentos

Analizar operaciones donde el descuento sea elevado y el margen porcentual
sea reducido para evitar crecimiento de ventas a costa de rentabilidad.

## 3. Potenciar los segmentos de mayor ticket

Diseñar campañas comerciales específicas para los segmentos que presentan
mayor valor promedio por operación.

## 4. Analizar las regiones de bajo desempeño

Comparar las regiones de menor facturación con las de mayor desempeño para
identificar oportunidades de crecimiento.

## 5. Hallazgos

### Hallazgo 1 — Categoría con mayores ventas

La categoría **HERRAMIENTAS** registra las mayores ventas netas, alcanzando **S/ 110K**.

### Hallazgo 2 — Canal con mayores ventas

El canal **TIENDA** concentra el mayor volumen de ventas netas, con **S/ *42.3 %*.

### Hallazgo 3 — Región con mayores ventas

La región **JUNIN** presenta el mayor nivel de ventas, alcanzando **S/ 112K**.

### Hallazgo 4 — Segmento con mayor ticket

El segmento **PROFESIONAL** presenta el mayor ticket promedio, con **S/ 118K** por operación.

### Hallazgo 5 — Mayor margen promedio

La categoría **HERRAMIENTAS** presenta el mayor margen promedio, con **S/ 105K** por operación.